

global.INTERVAL_SETTER_EXPECTATIONS = [
  { name: '-2', quality: 'M', step: 2 },
  { name: 'm3', quality: '+', step: 3 },
  { name: 'P5', quality: '-', step: 5 },
  { name: 'M6', quality: 'm', step: 6 },
  { name: '+7', quality: 'P', step: 7 },
];

global.INTERVAL_SEMITONES_SETTER_EXPECTATIONS = [
  { input: { name: 'P0', semitones: 0  }, output: 'P0' },
  { input: { name: 'm2', semitones: 1  }, output: 'M2' },
  { input: { name: 'M2', semitones: 2  }, output: 'M3' },
  { input: { name: 'm3', semitones: 3  }, output: '+4' },
  { input: { name: 'M3', semitones: 4  }, output: 'm6' },
  { input: { name: 'P4', semitones: 5  }, output: 'm7' },
  { input: { name: '+4', semitones: 6  }, output: 'P8' },
  { input: { name: 'P5', semitones: 7  }, output: 'M9' },
  { input: { name: 'm6', semitones: 8  }, output: 'M10' },
  { input: { name: 'M6', semitones: 9  }, output: '+11' },
  { input: { name: 'm7', semitones: 10 }, output: 'm13' },
  { input: { name: 'M7', semitones: 11 }, output: 'm14' },
  { input: { name: 'P8', semitones: 12 }, output: 'P15' },
];

global.INTERVAL_PARSE_EXPECTATIONS = [
  { input: 'P0', output: { quality: 'P', step: 0, semitones: 0 } },
  { input: '-2', output: { quality: '-', step: 2, semitones: 0 } },
  { input: 'm2', output: { quality: 'm', step: 2, semitones: 1 } },
  { input: 'M2', output: { quality: 'M', step: 2, semitones: 2 } },
  { input: '-3', output: { quality: '-', step: 3, semitones: 2 } },
  { input: '+2', output: { quality: '+', step: 2, semitones: 3 } },
  { input: 'm3', output: { quality: 'm', step: 3, semitones: 3 } },
  { input: 'M3', output: { quality: 'M', step: 3, semitones: 4 } },
  { input: '-4', output: { quality: '-', step: 4, semitones: 4 } },
  { input: '+3', output: { quality: '+', step: 3, semitones: 5 } },
  { input: 'P4', output: { quality: 'P', step: 4, semitones: 5 } },
  { input: '+4', output: { quality: '+', step: 4, semitones: 6 } },
  { input: '-5', output: { quality: '-', step: 5, semitones: 6 } },
  { input: 'P5', output: { quality: 'P', step: 5, semitones: 7 } },
  { input: '-6', output: { quality: '-', step: 6, semitones: 7 } },
  { input: '+5', output: { quality: '+', step: 5, semitones: 8 } },
  { input: 'm6', output: { quality: 'm', step: 6, semitones: 8 } },
  { input: 'M6', output: { quality: 'M', step: 6, semitones: 9 } },
  { input: '+6', output: { quality: '+', step: 6, semitones: 10 } },
  { input: 'm7', output: { quality: 'm', step: 7, semitones: 10 } },
  { input: 'M7', output: { quality: 'M', step: 7, semitones: 11 } },
  { input: '-8', output: { quality: '-', step: 8, semitones: 11 } },
  { input: 'P8', output: { quality: 'P', step: 8, semitones: 12 } },
  { input: '-9', output: { quality: '-', step: 9, semitones: 12 } },
  { input: '+8', output: { quality: '+', step: 8, semitones: 13 } },

  { input: 'm9', output: { quality: 'm', step: 9, semitones: 13 } },
  { input: 'M9', output: { quality: 'M', step: 9, semitones: 14 } },
  { input: '-10', output: { quality: '-', step: 10, semitones: 14 } },
  { input: '+9', output: { quality: '+', step: 9, semitones: 15 } },
  { input: 'm10', output: { quality: 'm', step: 10, semitones: 15 } },
  { input: 'M10', output: { quality: 'M', step: 10, semitones: 16 } },
  { input: '-11', output: { quality: '-', step: 11, semitones: 16 } },
  { input: 'P11', output: { quality: 'P', step: 11, semitones: 17 } },
  { input: '+10', output: { quality: '+', step: 10, semitones: 17 } },
  { input: '-12', output: { quality: '-', step: 12, semitones: 18 } },
  { input: '+11', output: { quality: '+', step: 11, semitones: 18 } },
  { input: 'P12', output: { quality: 'P', step: 12, semitones: 19 } },
  { input: '-13', output: { quality: '-', step: 13, semitones: 19 } },
  { input: 'm13', output: { quality: 'm', step: 13, semitones: 20 } },
  { input: '+12', output: { quality: '+', step: 12, semitones: 20 } },
  { input: 'M13', output: { quality: 'M', step: 13, semitones: 21 } },
  { input: '-14', output: { quality: '-', step: 14, semitones: 21 } },
  { input: 'm14', output: { quality: 'm', step: 14, semitones: 22 } },
  { input: '+13', output: { quality: '+', step: 13, semitones: 22 } },
  { input: 'M14', output: { quality: 'M', step: 14, semitones: 23 } },
  { input: '-15', output: { quality: '-', step: 15, semitones: 23 } },
  { input: 'P15', output: { quality: 'P', step: 15, semitones: 24 } },
  { input: '+14', output: { quality: '+', step: 14, semitones: 24 } },
  { input: '+15', output: { quality: '+', step: 15, semitones: 25 } },
];

global.INTERVAL_FROM_ROOT_EXPECTATIONS = [
  { input: { interval: 'P0', note: 'C0' }, output: 'C0' },
  { input: { interval: 'm2', note: 'C#0' }, output: 'D0' },
  { input: { interval: 'M2', note: 'D0' }, output: 'E0' },
  { input: { interval: 'm3', note: 'D#0' }, output: 'F#0' },
  { input: { interval: 'M3', note: 'E0' }, output: 'G#0' },
  { input: { interval: 'P4', note: 'F0' }, output: 'A#0' },
  { input: { interval: '+4', note: 'F#0' }, output: 'C1' },
  { input: { interval: 'P5', note: 'G0' }, output: 'D1' },
  { input: { interval: 'm6', note: 'G#0' }, output: 'E1' },
  { input: { interval: 'M6', note: 'A0' }, output: 'F#1' },
  { input: { interval: 'm7', note: 'A#0' }, output: 'G#1' },
  { input: { interval: 'M7', note: 'B0' }, output: 'A#1' },

  { input: { interval: 'P8', note: 'C1' }, output: 'C2' },
  { input: { interval: 'm9', note: 'C#1' }, output: 'D2' },
  { input: { interval: 'M9', note: 'D1' }, output: 'E2' },
  { input: { interval: 'm10', note: 'D#1' }, output: 'F#2' },
  { input: { interval: 'M10', note: 'E1' }, output: 'G#2' },
  { input: { interval: 'P11', note: 'F1' }, output: 'A#2' },
  { input: { interval: '+11', note: 'F#1' }, output: 'C3' },
  { input: { interval: 'P12', note: 'G1' }, output: 'D3' },
  { input: { interval: 'm13', note: 'G#1' }, output: 'E3' },
  { input: { interval: 'M13', note: 'A1' }, output: 'F#3' },
  { input: { interval: 'm14', note: 'A#1' }, output: 'G#3' },
  { input: { interval: 'M14', note: 'B1' }, output: 'A#3' },

  { input: { interval: 'P15', note: 'C2' }, output: 'C4' },
];



global.INTERVAL_FROM_SEMITONES_EXPECTATIONS = [
  { input: 0,  output: 'P0' },
  { input: 1,  output: 'm2' },
  { input: 2,  output: 'M2' },
  { input: 3,  output: 'm3' },
  { input: 4,  output: 'M3' },
  { input: 5,  output: 'P4' },
  { input: 6,  output: '+4' },
  { input: 7,  output: 'P5' },
  { input: 8,  output: 'm6' },
  { input: 9,  output: 'M6' },
  { input: 10, output: 'm7' },
  { input: 11, output: 'M7' },
  { input: 12, output: 'P8' },
  { input: 13, output: 'm9' },
  { input: 14, output: 'M9' },
  { input: 15, output: 'm10' },
  { input: 16, output: 'M10' },
  { input: 17, output: 'P11' },
  { input: 18, output: '+11' },
  { input: 19, output: 'P12' },
  { input: 20, output: 'm13' },
  { input: 21, output: 'M13' },
  { input: 22, output: 'm14' },
  { input: 23, output: 'M14' },
  { input: 24, output: 'P15' },
];


global.COUNT_SEMITONES_EXPECTATIONS = [
  { input: { bass: 'C0',  treble: 'C0' },  output: 0 },
  { input: { bass: 'C#0', treble: 'D0' },  output: 1 },
  { input: { bass: 'D0',  treble: 'E0' },  output: 2 },
  { input: { bass: 'D#0', treble: 'F#0' }, output: 3 },

  { input: { bass: 'E0',  treble: 'G#0' }, output: 4 },
  { input: { bass: 'F0',  treble: 'A#0' }, output: 5 },
  { input: { bass: 'F#0', treble: 'C1' },  output: 6 },
  { input: { bass: 'G0',  treble: 'D1' },  output: 7 },

  { input: { bass: 'G#0', treble: 'E1' },  output: 8 },
  { input: { bass: 'A0',  treble: 'F#1' }, output: 9 },
  { input: { bass: 'A#0', treble: 'G#1' }, output: 10 },
  { input: { bass: 'B0',  treble: 'A#1' }, output: 11 },

  { input: { bass: 'C1',  treble: 'C2' },  output: 12 },
  { input: { bass: 'C#1', treble: 'D2' },  output: 13 },
  { input: { bass: 'D1',  treble: 'E2' },  output: 14 },
  { input: { bass: 'D#1', treble: 'F#2' }, output: 15 },
];

global.INTERVAL_INVERT_EXPECTATIONS = [
  // TODO: are these compound inversions correct?
  { input: 'P0', output: 'P8' },
  { input: 'm2', output: 'M7' },
  { input: 'M2', output: 'm7' },
  { input: 'm3', output: 'M6' },
  { input: 'M3', output: 'm6' },
  { input: 'P4', output: 'P5' },
  { input: '+4', output: '+4' },
  { input: 'P5', output: 'P4' },
  { input: 'm6', output: 'M3' },
  { input: 'M6', output: 'm3' },
  { input: 'm7', output: 'M2' },
  { input: 'M7', output: 'm2' },

  { input: 'P8' , output:'P0' },
  { input: 'm9', output: 'M7' },
  { input: 'M9', output: 'm7' },
  { input: 'm10', output:'M6' },
  { input: 'M10', output:'m6' },
  { input: 'P11', output:'P5' },
  { input: '+11', output:'+4' },
  { input: 'P12', output:'P4' },
  { input: 'm13', output:'M3' },
  { input: 'M13', output:'m3' },
  { input: 'm14', output:'M2' },
  { input: 'M14', output:'m2' },
  { input: 'P15', output:'P8' },
];
